# Generated by Django 5.2.12 on 2026-03-09 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("exploration", "Regional Exploration"),
                            ("education", "Educational Resources"),
                            ("discussion", "Community Discussions"),
                            ("contribution", "Knowledge Contributions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="🎯", max_length=50)),
                ("participant_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["activity_type"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Tunisian phone number.",
                                regex="^\\+?2?1?6?\\d{8}$",
                            )
                        ],
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("learner", "Learner"),
                            ("contributor", "Contributor"),
                            ("volunteer", "Research Volunteer"),
                            ("ambassador", "Community Ambassador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("governorate", models.CharField(max_length=50, unique=True)),
                ("delegation_count", models.IntegerField(default=0)),
                ("participant_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["governorate"],
            },
        ),
    ]
